
--带有相互引用的参照约束，先导入数据，后添加约束！
ALTER TABLE "URP_DORMITORY" ADD CONSTRAINT "FK_URP_DORMITORY_MANAGER" FOREIGN KEY ("MANAGER") REFERENCES "URP_STUDENT" ("STU_NO");

ALTER TABLE "URP_COLLEGE" ADD CONSTRAINT "FK_URP_COLLEGE_PRESIDENT" FOREIGN KEY ("PRESIDENT") REFERENCES "URP_TEACHER" ("TEACHER_NO");

ALTER TABLE "URP_DEPARTMENT" ADD CONSTRAINT "FK_URP_DEPARTMENT_COLLEGE_NO" FOREIGN KEY ("COLLEGE_NO") REFERENCES "URP_COLLEGE" ("COLLEGE_NO");
ALTER TABLE "URP_DEPARTMENT" ADD CONSTRAINT "FK_URP_DEPARTMENT_HEADER" FOREIGN KEY ("DEPART_HEADER") REFERENCES "URP_TEACHER" ("TEACHER_NO");

ALTER TABLE "URP_TEACHER" ADD CONSTRAINT "FK_URP_TEACHER_COLLEGE_NO" FOREIGN KEY ("COLLEGE_NO") REFERENCES "URP_COLLEGE" ("COLLEGE_NO");
ALTER TABLE "URP_TEACHER" ADD CONSTRAINT "FK_URP_TEACHER_DEPART_NO" FOREIGN KEY ("DEPART_NO") REFERENCES "URP_DEPARTMENT" ("DEPART_NO");


 

